# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asiatici/epfl/memory-coalescer/vivado/spmv/spmv-hls/TopLevel/TopLevel.srcs/sources_1/ip/spmv_mult_axis_0_2/spmv_mult_axis_0.xci
# IP: The module: 'spmv_mult_axis_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asiatici/epfl/memory-coalescer/vivado/spmv/spmv-hls/TopLevel/TopLevel.srcs/sources_1/ip/spmv_mult_axis_0_2/constraints/spmv_mult_axis_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spmv_mult_axis_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/asiatici/epfl/memory-coalescer/vivado/spmv/spmv-hls/TopLevel/TopLevel.srcs/sources_1/ip/spmv_mult_axis_0_2/spmv_mult_axis_0.xci
# IP: The module: 'spmv_mult_axis_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asiatici/epfl/memory-coalescer/vivado/spmv/spmv-hls/TopLevel/TopLevel.srcs/sources_1/ip/spmv_mult_axis_0_2/constraints/spmv_mult_axis_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spmv_mult_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
