// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xlen_stream.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XLen_stream_CfgInitialize(XLen_stream *InstancePtr, XLen_stream_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XLen_stream_Start(XLen_stream *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_AP_CTRL) & 0x80;
    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XLen_stream_IsDone(XLen_stream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XLen_stream_IsIdle(XLen_stream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XLen_stream_IsReady(XLen_stream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XLen_stream_EnableAutoRestart(XLen_stream *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XLen_stream_DisableAutoRestart(XLen_stream *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_AP_CTRL, 0);
}

void XLen_stream_Set_val_size(XLen_stream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_VAL_SIZE_DATA, Data);
}

u32 XLen_stream_Get_val_size(XLen_stream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_VAL_SIZE_DATA);
    return Data;
}

void XLen_stream_Set_output_size(XLen_stream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_OUTPUT_SIZE_DATA, Data);
}

u32 XLen_stream_Get_output_size(XLen_stream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_OUTPUT_SIZE_DATA);
    return Data;
}

void XLen_stream_Set_offset(XLen_stream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_OFFSET_DATA, Data);
}

u32 XLen_stream_Get_offset(XLen_stream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_OFFSET_DATA);
    return Data;
}

void XLen_stream_InterruptGlobalEnable(XLen_stream *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_GIE, 1);
}

void XLen_stream_InterruptGlobalDisable(XLen_stream *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_GIE, 0);
}

void XLen_stream_InterruptEnable(XLen_stream *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_IER);
    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_IER, Register | Mask);
}

void XLen_stream_InterruptDisable(XLen_stream *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_IER);
    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_IER, Register & (~Mask));
}

void XLen_stream_InterruptClear(XLen_stream *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLen_stream_WriteReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_ISR, Mask);
}

u32 XLen_stream_InterruptGetEnabled(XLen_stream *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_IER);
}

u32 XLen_stream_InterruptGetStatus(XLen_stream *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLen_stream_ReadReg(InstancePtr->Axilites_BaseAddress, XLEN_STREAM_AXILITES_ADDR_ISR);
}

