// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XLEN_STREAM_H
#define XLEN_STREAM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xlen_stream_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XLen_stream_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XLen_stream;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XLen_stream_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XLen_stream_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XLen_stream_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XLen_stream_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XLen_stream_Initialize(XLen_stream *InstancePtr, u16 DeviceId);
XLen_stream_Config* XLen_stream_LookupConfig(u16 DeviceId);
int XLen_stream_CfgInitialize(XLen_stream *InstancePtr, XLen_stream_Config *ConfigPtr);
#else
int XLen_stream_Initialize(XLen_stream *InstancePtr, const char* InstanceName);
int XLen_stream_Release(XLen_stream *InstancePtr);
#endif

void XLen_stream_Start(XLen_stream *InstancePtr);
u32 XLen_stream_IsDone(XLen_stream *InstancePtr);
u32 XLen_stream_IsIdle(XLen_stream *InstancePtr);
u32 XLen_stream_IsReady(XLen_stream *InstancePtr);
void XLen_stream_EnableAutoRestart(XLen_stream *InstancePtr);
void XLen_stream_DisableAutoRestart(XLen_stream *InstancePtr);

void XLen_stream_Set_val_size(XLen_stream *InstancePtr, u32 Data);
u32 XLen_stream_Get_val_size(XLen_stream *InstancePtr);
void XLen_stream_Set_output_size(XLen_stream *InstancePtr, u32 Data);
u32 XLen_stream_Get_output_size(XLen_stream *InstancePtr);
void XLen_stream_Set_offset(XLen_stream *InstancePtr, u32 Data);
u32 XLen_stream_Get_offset(XLen_stream *InstancePtr);

void XLen_stream_InterruptGlobalEnable(XLen_stream *InstancePtr);
void XLen_stream_InterruptGlobalDisable(XLen_stream *InstancePtr);
void XLen_stream_InterruptEnable(XLen_stream *InstancePtr, u32 Mask);
void XLen_stream_InterruptDisable(XLen_stream *InstancePtr, u32 Mask);
void XLen_stream_InterruptClear(XLen_stream *InstancePtr, u32 Mask);
u32 XLen_stream_InterruptGetEnabled(XLen_stream *InstancePtr);
u32 XLen_stream_InterruptGetStatus(XLen_stream *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
