// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xlen_stream.h"

extern XLen_stream_Config XLen_stream_ConfigTable[];

XLen_stream_Config *XLen_stream_LookupConfig(u16 DeviceId) {
	XLen_stream_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XLEN_STREAM_NUM_INSTANCES; Index++) {
		if (XLen_stream_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XLen_stream_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XLen_stream_Initialize(XLen_stream *InstancePtr, u16 DeviceId) {
	XLen_stream_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XLen_stream_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XLen_stream_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

