// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSPMV_MULT_AXIS_H
#define XSPMV_MULT_AXIS_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xspmv_mult_axis_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XSpmv_mult_axis_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XSpmv_mult_axis;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSpmv_mult_axis_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSpmv_mult_axis_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSpmv_mult_axis_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSpmv_mult_axis_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSpmv_mult_axis_Initialize(XSpmv_mult_axis *InstancePtr, u16 DeviceId);
XSpmv_mult_axis_Config* XSpmv_mult_axis_LookupConfig(u16 DeviceId);
int XSpmv_mult_axis_CfgInitialize(XSpmv_mult_axis *InstancePtr, XSpmv_mult_axis_Config *ConfigPtr);
#else
int XSpmv_mult_axis_Initialize(XSpmv_mult_axis *InstancePtr, const char* InstanceName);
int XSpmv_mult_axis_Release(XSpmv_mult_axis *InstancePtr);
#endif

void XSpmv_mult_axis_Start(XSpmv_mult_axis *InstancePtr);
u32 XSpmv_mult_axis_IsDone(XSpmv_mult_axis *InstancePtr);
u32 XSpmv_mult_axis_IsIdle(XSpmv_mult_axis *InstancePtr);
u32 XSpmv_mult_axis_IsReady(XSpmv_mult_axis *InstancePtr);
void XSpmv_mult_axis_EnableAutoRestart(XSpmv_mult_axis *InstancePtr);
void XSpmv_mult_axis_DisableAutoRestart(XSpmv_mult_axis *InstancePtr);

void XSpmv_mult_axis_Set_val_size(XSpmv_mult_axis *InstancePtr, u32 Data);
u32 XSpmv_mult_axis_Get_val_size(XSpmv_mult_axis *InstancePtr);
void XSpmv_mult_axis_Set_output_size(XSpmv_mult_axis *InstancePtr, u32 Data);
u32 XSpmv_mult_axis_Get_output_size(XSpmv_mult_axis *InstancePtr);
void XSpmv_mult_axis_Set_vect_mem(XSpmv_mult_axis *InstancePtr, u32 Data);
u32 XSpmv_mult_axis_Get_vect_mem(XSpmv_mult_axis *InstancePtr);

void XSpmv_mult_axis_InterruptGlobalEnable(XSpmv_mult_axis *InstancePtr);
void XSpmv_mult_axis_InterruptGlobalDisable(XSpmv_mult_axis *InstancePtr);
void XSpmv_mult_axis_InterruptEnable(XSpmv_mult_axis *InstancePtr, u32 Mask);
void XSpmv_mult_axis_InterruptDisable(XSpmv_mult_axis *InstancePtr, u32 Mask);
void XSpmv_mult_axis_InterruptClear(XSpmv_mult_axis *InstancePtr, u32 Mask);
u32 XSpmv_mult_axis_InterruptGetEnabled(XSpmv_mult_axis *InstancePtr);
u32 XSpmv_mult_axis_InterruptGetStatus(XSpmv_mult_axis *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
