// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_mult_axis_entry (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        val_size,
        output_size,
        val_size_out_din,
        val_size_out_full_n,
        val_size_out_write,
        output_size_out_din,
        output_size_out_full_n,
        output_size_out_write,
        output_size_out1_din,
        output_size_out1_full_n,
        output_size_out1_write,
        vect_mem,
        vect_mem_out_din,
        vect_mem_out_full_n,
        vect_mem_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] val_size;
input  [31:0] output_size;
output  [31:0] val_size_out_din;
input   val_size_out_full_n;
output   val_size_out_write;
output  [31:0] output_size_out_din;
input   output_size_out_full_n;
output   output_size_out_write;
output  [31:0] output_size_out1_din;
input   output_size_out1_full_n;
output   output_size_out1_write;
input  [31:0] vect_mem;
output  [31:0] vect_mem_out_din;
input   vect_mem_out_full_n;
output   vect_mem_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg val_size_out_write;
reg output_size_out_write;
reg output_size_out1_write;
reg vect_mem_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    val_size_out_blk_n;
reg    output_size_out_blk_n;
reg    output_size_out1_blk_n;
reg    vect_mem_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        output_size_out1_blk_n = output_size_out1_full_n;
    end else begin
        output_size_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        output_size_out1_write = 1'b1;
    end else begin
        output_size_out1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        output_size_out_blk_n = output_size_out_full_n;
    end else begin
        output_size_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        output_size_out_write = 1'b1;
    end else begin
        output_size_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        val_size_out_blk_n = val_size_out_full_n;
    end else begin
        val_size_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        val_size_out_write = 1'b1;
    end else begin
        val_size_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        vect_mem_out_blk_n = vect_mem_out_full_n;
    end else begin
        vect_mem_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        vect_mem_out_write = 1'b1;
    end else begin
        vect_mem_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (vect_mem_out_full_n == 1'b0) | (output_size_out1_full_n == 1'b0) | (output_size_out_full_n == 1'b0) | (val_size_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign output_size_out1_din = output_size;

assign output_size_out_din = output_size;

assign start_out = real_start;

assign val_size_out_din = val_size;

assign vect_mem_out_din = vect_mem;

endmodule //spmv_mult_axis_entry
