// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xspmv_mult_axis.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSpmv_mult_axis_CfgInitialize(XSpmv_mult_axis *InstancePtr, XSpmv_mult_axis_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSpmv_mult_axis_Start(XSpmv_mult_axis *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_AP_CTRL) & 0x80;
    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSpmv_mult_axis_IsDone(XSpmv_mult_axis *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSpmv_mult_axis_IsIdle(XSpmv_mult_axis *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSpmv_mult_axis_IsReady(XSpmv_mult_axis *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSpmv_mult_axis_EnableAutoRestart(XSpmv_mult_axis *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XSpmv_mult_axis_DisableAutoRestart(XSpmv_mult_axis *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_AP_CTRL, 0);
}

void XSpmv_mult_axis_Set_val_size(XSpmv_mult_axis *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_VAL_SIZE_DATA, Data);
}

u32 XSpmv_mult_axis_Get_val_size(XSpmv_mult_axis *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_VAL_SIZE_DATA);
    return Data;
}

void XSpmv_mult_axis_Set_output_size(XSpmv_mult_axis *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_OUTPUT_SIZE_DATA, Data);
}

u32 XSpmv_mult_axis_Get_output_size(XSpmv_mult_axis *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_OUTPUT_SIZE_DATA);
    return Data;
}

void XSpmv_mult_axis_Set_vect_mem(XSpmv_mult_axis *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_VECT_MEM_DATA, Data);
}

u32 XSpmv_mult_axis_Get_vect_mem(XSpmv_mult_axis *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_VECT_MEM_DATA);
    return Data;
}

void XSpmv_mult_axis_InterruptGlobalEnable(XSpmv_mult_axis *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_GIE, 1);
}

void XSpmv_mult_axis_InterruptGlobalDisable(XSpmv_mult_axis *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_GIE, 0);
}

void XSpmv_mult_axis_InterruptEnable(XSpmv_mult_axis *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_IER);
    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_IER, Register | Mask);
}

void XSpmv_mult_axis_InterruptDisable(XSpmv_mult_axis *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_IER);
    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_IER, Register & (~Mask));
}

void XSpmv_mult_axis_InterruptClear(XSpmv_mult_axis *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSpmv_mult_axis_WriteReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_ISR, Mask);
}

u32 XSpmv_mult_axis_InterruptGetEnabled(XSpmv_mult_axis *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_IER);
}

u32 XSpmv_mult_axis_InterruptGetStatus(XSpmv_mult_axis *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSpmv_mult_axis_ReadReg(InstancePtr->Axilites_BaseAddress, XSPMV_MULT_AXIS_AXILITES_ADDR_ISR);
}

