// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xspmv_mult_axis.h"

extern XSpmv_mult_axis_Config XSpmv_mult_axis_ConfigTable[];

XSpmv_mult_axis_Config *XSpmv_mult_axis_LookupConfig(u16 DeviceId) {
	XSpmv_mult_axis_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSPMV_MULT_AXIS_NUM_INSTANCES; Index++) {
		if (XSpmv_mult_axis_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSpmv_mult_axis_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSpmv_mult_axis_Initialize(XSpmv_mult_axis *InstancePtr, u16 DeviceId) {
	XSpmv_mult_axis_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSpmv_mult_axis_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSpmv_mult_axis_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

