#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jul 04 10:47:10 CEST 2018
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim TopLevelTB_behav -key {Behavioral:sim_1:Functional:TopLevelTB} -tclbatch TopLevelTB.tcl -view /home/asiatici/epfl/memory-coalescer/vivado/spmv/spmv-hls/TopLevel/TopLevelTB_behav.wcfg -log simulate.log
